// Code generated by "stringer -type=Token"; DO NOT EDIT

package token

import "fmt"

const _Token_name = "IllegalEOSWhitespaceInlineStringIntegerCommaPipeDotLeftBracketRightBracketColon"

var _Token_index = [...]uint8{0, 7, 10, 20, 32, 39, 44, 48, 51, 62, 74, 79}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
